### ISSUE TITLE
Make FAQs collapsible

### ISSUE THREAD

**Issue by nainardev** [anonaddy/anonaddy.com#2]
There are many FAQs and to make scrolling easier, it needs to be collapsible. Maybe, details/summary tag may help

**Comment by willbrowningme** [comment]
Thanks, I agree that it would make it easier to scroll. The main reason I haven't done this is because I didn't want to add javascript to pages that didn't need it. The only javascript currently used on the site is for the search functionality and some code highlighting on the blog/help pages.

I'll have a look at any other ways to acheive a similar thing.

**Comment by nainardev** [comment]
use details and summary tag and add some CSS . It'll be fine without js

**Comment by MartijnCuppens** [comment]
Watch out with hiding text. Users often navigate by using the browser search. 

An alternative could be to add anchor links to the top of the page that link to the titles (if you can manage to add unique id's to the headings somehow).

**Comment by willbrowningme** [comment]
@MartijnCuppens Thanks, just updated the site now to include links to each question at the top of the page.
